### ISSUE TITLE
Problems with different locale for database or database locking

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#423]
The stacktrace shows that there is a problem changing the locale for the database connection. However, is also shows a thrown `android.database.sqlite.SQLiteDatabaseLockedException` This needs to be investigated further.

See possible solution: http://stackoverflow.com/a/19491862/738903

Stacktrace:

```java
java.lang.RuntimeException: Unable to resume activity {com.liato.bankdroid/com.liato.bankdroid.MainActivity}: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.liato.bankdroid/databases/data' to 'sv_SE'.
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2854)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2883)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2321)
at android.app.ActivityThread.access$600(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:5225)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.liato.bankdroid/databases/data' to 'sv_SE'.
at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:393)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:812)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:797)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:702)
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:905)
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:235)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
at com.liato.bankdroid.db.DBAdapter.open(DBAdapter.java:69)
at com.liato.bankdroid.banking.BankFactory.banksFromDb(BankFactory.java:412)
at com.liato.bankdroid.MainActivity.refreshView(MainActivity.java:142)
at com.liato.bankdroid.MainActivity.onResume(MainActivity.java:131)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
at android.app.Activity.performResume(Activity.java:5211)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2844)
... 12 more
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
... 31 more
```

**Comment by goober** [comment]
Duplicate of #189
