### ISSUE TITLE
Dismiss dialog after activity has finished causes IllegalArgumentException 

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#424]
Possible solution: http://stackoverflow.com/questions/2745061/java-lang-illegalargumentexception-view-not-attached-to-window-manager

http://stackoverflow.com/a/18665887/738903

```java
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{44b909c0 V.E..... R.....I. 0,0-1026,436} not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:370)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:299)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
at android.app.Dialog.dismissDialog(Dialog.java:337)
at android.app.Dialog.dismiss(Dialog.java:320)
at com.liato.bankdroid.DataRetrieverTask.onPostExecute(DataRetrieverTask.java:132)
at com.liato.bankdroid.DataRetrieverTask.onPostExecute(DataRetrieverTask.java:38)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5135)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by goober** [comment]
Could be the root cause of this stacktrace as well:

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@430201e8 is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:536)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
at android.app.Dialog.show(Dialog.java:294)
at com.liato.bankdroid.BankEditActivity$DataRetrieverTask.onPostExecute(BankEditActivity.java:294)
at com.liato.bankdroid.BankEditActivity$DataRetrieverTask.onPostExecute(BankEditActivity.java:214)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5135)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by goober** [comment]
Root cause of this issue is that a dialog is open and then disappears when the user rotates the screen. When the background task finishes the dialog has already been removed and this causes the app to crash.
