### ISSUE TITLE
NullPointerException for Coop

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#430]
```java
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
at com.liato.bankdroid.banking.banks.coop.Coop.preLogin(Coop.java:174)
at com.liato.bankdroid.banking.banks.coop.Coop.login(Coop.java:195)
at com.liato.bankdroid.banking.banks.coop.Coop.update(Coop.java:231)
at com.liato.bankdroid.DataRetrieverTask.doInBackground(DataRetrieverTask.java:87)
at com.liato.bankdroid.DataRetrieverTask.doInBackground(DataRetrieverTask.java:38)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

**Comment by fredrike** [comment]
Any more info than this, when does it occur?

**Comment by robho** [comment]
I get a crash when entering invalid login information with coop. I don't know if this is the same crash as reported above though..

**Comment by goober** [comment]
I just have a crash report with the exception. No messages was attached.

**Comment by fredrike** [comment]
Ah, it is on line 174. There are no-longer any pageGuid on Coop's page.

A login is instead done via `https://www.coop.se/Personliga-Baren/Logga-in/?method=Login` with this header: `X-Requested-With: XMLHttpRequest` and post data: `{"isBar":"true","username":USER,"password":PASS}`

I.e. most of the prelogin can be changed to just an urlopen with above data..
