### ISSUE TITLE
Application crashes for notifications if SonyMobile LiveView is enabled.

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#434]
```java
java.lang.RuntimeException: Unable to create service com.liato.bankdroid.liveview.LiveViewService: android.content.res.Resources$NotFoundException: Resource ID #0x0
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2514)
at android.app.ActivityThread.access$1600(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:4987)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
at android.content.res.Resources.getValue(Resources.java:1032)
at android.content.res.Resources.openRawResource(Resources.java:957)
at android.content.res.Resources.openRawResource(Resources.java:939)
at com.liato.bankdroid.liveview.PluginUtils.storeIconToFile(PluginUtils.java:77)
at com.liato.bankdroid.liveview.LiveViewService.onCreate(LiveViewService.java:132)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2504)
... 10 more
```

**Comment by goober** [comment]
Caused by [LiveViewService.java#L131] (https://github.com/liato/android-bankdroid/blob/f02bdfc3df24d6ddfa3c4343ae4bacc9d361ccb9/app/src/main/java/com/liato/bankdroid/liveview/LiveViewService.java#L131)

The method is trying to get the resource `app/src/main/res/drawable/icon.png` which was removed in 040e3df84d128e2aae87a107802f7c5ea873dc8c
